server:
  port: 2007
spring:
  application:
    name: eurekaserverconfig
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/75101/project-config
          #文件夹路径
          searchPaths: springboot-config
          username: 751016301@qq.com
          password:  qqRQ1994
      label: master
  rabbitmq:
    host: 172.17.190.104
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:2000/eureka/
