eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2000/eureka/
server:
  port: 2006
spring:
  application:
    name: service-zuul
zuul:
  routes:
    eurekaclientbase:
      path: /api-a/**
      #serviceId: eurekaclientbase
    eurekaclientfeign:
      path: /api-b/**
      #serviceId: eurekaclientfeign
